#!/usr/bin/env python
"""
Show the dataflow template from the reduced file using pretty-printed JSON.
"""

from __future__ import print_function

import sys
import json
import re

# Match the following on the first line:
# - initial comment ("#" or "//")
# - the word template or template_data, perhaps in single or double quotes
# - optional separator (":" or "=")
# - open brace of template

TEMPLATE = re.compile(r"^(#|//) *([\"']?template(_data)?[\"']?)? *[:=]? *\{")

def main():
    if len(sys.argv) < 2:
        print("usage: show_template datafile")
        sys.exit()
    with open(sys.argv[1]) as fid:
        line = fid.readline()
        template = TEMPLATE.sub('{', line)
        print(json.dumps(json.loads(template), indent=2))

if __name__ == "__main__":
    main()
