name: UpdateSourceDist

on:
  push:
    branches: [ main ]

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        mkdir unstable

    - name: Build source distribution
      run: |
        echo $GITHUB_SHA > dataflow/git_revision
        python setup.py sdist --formats=zip
        cp dist/*.zip unstable/reductus-latest-source.zip
        ls -l unstable/

    # See the following for how to upload to a release
    #  https://eugene-babichenko.github.io/blog/2020/05/09/github-actions-cross-platform-auto-releases/
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          unstable/*

  publish:
    needs: test_and_build
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve all artifacts
      uses: actions/download-artifact@v4.1.7
      with:
        name: artifacts

    - name: show files
      run: |
        ls * -l

    - name: Update unstable release
      uses: johnwbyrd/update-release@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release: unstable
        tag: sid
        files: reductus-latest-source.zip

